# Generated by Django 4.2 on 2023-05-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beertype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brewing_type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('founded_year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('alcohol_content', models.DecimalField(decimal_places=2, max_digits=4)),
                ('original_gravity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recommended_serving_temperature', models.IntegerField()),
                ('is_organic', models.BooleanField()),
                ('clarity', models.CharField(max_length=100)),
                ('yeast', models.CharField(max_length=100)),
                ('is_gluten_free', models.BooleanField()),
                ('description', models.TextField()),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rating.brewery')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rating.beertype')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
                ('entry', models.IntegerField()),
                ('body', models.IntegerField()),
                ('finish', models.IntegerField()),
                ('carbonation', models.IntegerField()),
                ('acidity', models.IntegerField()),
                ('bitterness', models.IntegerField()),
                ('drinkability', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rating.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('beer', 'user')},
            },
        ),
    ]
