# Generated by Django 4.2 on 2023-04-20 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brewery', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('ibu', models.FloatField()),
                ('description', models.TextField()),
                ('preis', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(default=0)),
                ('aroma_rating', models.IntegerField(default=0)),
                ('appearance_rating', models.IntegerField(default=0)),
                ('taste_rating', models.IntegerField(default=0)),
                ('mouthfeel_rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('beer', 'user')},
            },
        ),
    ]
