# Generated by Django 4.2 on 2023-04-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_rating_date_created_remove_rating_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='appearance_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='aroma_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mouthfeel_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='taste_rating',
        ),
    ]
