# Generated by Django 4.2 on 2023-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_rating_unique_together_rating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.CharField(max_length=100),
        ),
    ]
